import type { NextPage } from 'next';
import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Aidan Portfolio</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<section className='min-h-screen'>
					<nav className='py-10'>
						<h1>Hello World</h1>
						<ul>
							<li>Blog</li>
							<li>Contact Me</li>
							<li>
								<BsFillMoonStarsFill />
							</li>
						</ul>
					</nav>
				</section>
			</main>

			<footer></footer>
		</div>
	);
};

export default Home;
