name: CI
on:
  push:
    branches: [ testing-workflows ]
  workflow_dispatch:
jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Git Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node.js Dependencies
        run: npm ci
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Check out Git Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install NPM Dependencies
        run: npm install

      - name: Install Amplify CLI
        run:
          npm install -g @aws-amplify/cli


      #      - name: Configure AWS  Credentials
      #        uses: aws-actions/configure-aws-credentials@v1
      #        with:
      #          aws-region: eu-west-2
      #          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #      - name: Configure AWS Credentials
      #        uses: aws-actions/configure-aws-credentials@v2
      #        run: amplify configure
      #        with:
      #          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #          role-to-assume: ${{ secrets.AWS_IAM_USER}}
      #          aws-region: eu-west-2
      - name: Configure AWS Credentials
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-west-2



      - name: Pull App From AWS Amplify
        run: amplify pull

      - name: Check Amplify Status
        run:
          amplify status
          amplify env list

      - name: Deploy To AWS
        run: amplify push --force

      - name: Commit Amplify Files
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: Apply automatic changes
          file_pattern: amplify/* amplifyconfiguration.json awsconfiguration.json

      - name: Remove AWS Amplify CLI Package
        run: npm uninstall -g @aws-amplify/cli

